### ISSUE TITLE
Date computation is wrong in DST regions

### ISSUE THREAD

**Issue by lf-** [kmc059000/octordle#6]
Reporting a bug I just fixed in https://github.com/jades-projects/lesble that also affects Octordle:

When you are in a DST region, the time zone on the start-date object of the puzzles is in standard time, and now summer time is in effect (at least, in North America). The result of this, for octordle, is that the time that the puzzles show up is 1am, since the timestamp computation is correct, but it is starting from midnight *in a different time zone, offset by an hour*.

The way I solved it in mine is to round instead of floor'ing the difference in days between the two midnight timestamps. The "time to next puzzle" feature also needs adjusting, possibly by adding 1 day to the date then setting the time to zero to get a Date of tomorrow at midnight.

**Comment by kmc059000** [comment]
Thanks, this should be fixed now.

**Comment by lf-** [comment]
I think it's not fixed, I still am getting daily number 52 right now (between midnight and 1am), which I played yesterday. Filed a PR.
